# Generated by Django 4.2 on 2024-05-14 12:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
